version: '3'
services:
  app:
    image: node:carbon-alpine
    command: node dist/index.js
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
    working_dir: /home/app
  worker:
    image: node:carbon-alpine
    command: node dist/jobs/fib.js
    volumes:
      - .:/home/app
    working_dir: /home/app
  rabbitmq:
    image: rabbitmq:3.7-alpine
